= Parameters

The parent key for all of the following parameters is `home_assistant`.

== `namespace`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
annotations: {}
labels: {}
name: app-${_instance}
----

The namespace in which to deploy this component.


== `resources`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
home_assistant:
  requests: {}
  limits: {}
influxdb:
  requests: {}
  limits: {}
----

Configure resource requests and limits.


== `prometheus`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: false <1>
service: {} <2>
----
<1> Enable servicemonitor.
<2> Additional servicemonitor spec.

Enable/configure service monitor.


== `config`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
ingress: <1>
  enabled: false
  url: home-assistant.local
  tls: true
  annotations: {}
persistence: <2>
  mode: ReadWriteOnce
  size: 1Gi
  class: ''
extra: <3>
  enabled: false
  content: ""
----
<1> Configure home-assistant ingress.
<2> Configure persistence for home-assistant.
<2> Enable managing `configuration.yaml` with configmap.

Configure home-assistant.


== `influxdb`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: true <1>
retention: '50w' <2>
persistence: <3>
  mode: ReadWriteOnce
  size: 10Gi
  class: ''
----
<1> Enable influxdb.
<2> Configure retention period.
<3> Configure persistence for influxdb.

Enable/configure influxdb2 as timeseries backend.


== Example

[source,yaml]
----
namespace: example-namespace
----
