= Parameters

The parent key for all of the following parameters is `home_assistant`.

== `namespace`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
annotations: {}
labels: {}
name: ${_instance}
----

The namespace in which to deploy this component.


== `replicaCount`

[horizontal]
type:: integer
default:: 1

The number of home-assistant replicas.


== `resources`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
home_assistant:
  requests: {}
  limits: {}
influxdb:
  requests: {}
  limits: {}
----

Configure resource requests and limits.


== `storage`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
home_assistant:
  mode: ReadWriteOnce <1>
  size: 1Gi <2>
  class: '' <3>
influxdb:
  mode: ReadWriteOnce
  size: 10Gi
  class: ''
----
<1> Configure access mode.
<2> Configure storage requeust.
<3> Configure storageclass.

Configure persistent volume claims.


== `prometheus`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: false <1>
service: {} <2>
----
<1> Enable servicemonitor.
<2> Additional servicemonitor spec.

Enable/configure service monitor.


== `ingress`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: false <1>
host: home-assistant.local <2>
tls:
  enabled: true <3>
  issuer: 'letsencrypt-production' <4>
----
<1> Enable home-assistant ingress.
<2> Configure URL.
<3> Enable TLS for ingress.
<4> Configure cluster-issuer (cert-manager).

Enable/configure home-assistant ingress.


== `config`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: false
extra: ""
----
<1> Enable config by configmap.
<2> Additional configuration.

Enable managing `configuration.yaml` with configmap.


== `influxdb`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
enabled: true <1>
retention: '50w' <2>
----
<1> Enable influxdb.
<2> Configure retention period.

Enable/configure influxdb2 as timeseries backend.


== Example

[source,yaml]
----
namespace: example-namespace
----
